# Configuração de cache para otimizar a entrega de imagens do Next.js
[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "http://gringastylebr.com.br/*"
  to = "https://gringastylebr.com.br/:splat"
  status = 301

[[redirects]]
  from = "https://gringa-style.netlify.app/*"
  to = "https://gringastylebr.com.br/:splat"
  status = 301

[[redirects]]
  from = "https://gringastyle.netlify.app/*"
  to = "https://gringastylebr.com.br/:splat"
  status = 301

[[redirects]]
  from = "https://*.netlify.app/*"
  to = "https://gringastylebr.com.br/:splat"
  status = 301

[[redirects]]
  from = "http://www.gringastylebr.com.br/*"
  to = "https://gringastylebr.com.br/:splat"
  status = 301